### ISSUE TITLE
Vertical tab is erroneously included in the blank character class

### ISSUE THREAD

**Issue by Aster89** [boostorg/regex#111]
Per POSIX, `[[:blank:]]` should only contain space and (horizontal) tab, the vertical tab being in `[[:space:]]`. However, the following code shows that boost puts the vertical space in `[[:blank:]]` too.

```
#include <regex>
#include <assert.h>
#include <boost/regex.hpp>
#include <iostream>
#include <boost/version.hpp>
int main() {
    std::cout << BOOST_VERSION % 100 << ' ' << BOOST_VERSION / 100 % 1000 << ' ' << BOOST_VERSION / 100000 << '\n';
    const auto VT = "\x0B";
    assert( std::regex_match(VT  , std::regex{"^[[:space:]]+$"}));
    assert(!std::regex_match(VT  , std::regex{"^[[:blank:]]+$"}));
    assert( boost::regex_match(VT  , boost::regex{"^[[:space:]]+$"}));
    assert(!boost::regex_match(VT  , boost::regex{"^[[:blank:]]+$"})); // fails
}
```

**Comment by JohnAlt2** [comment]
Testing with what is probably 1.64.0 release does not show [:blank:] detecting vertical tabs in practise. 
See image:
![image](https://user-images.githubusercontent.com/46526650/193460141-f2a9b92c-9457-4f4d-9645-1f3cbea71077.png)

What file was this seen in?

Marking this ticket for closure in a month if there is no further info.

**Comment by Aster89** [comment]
I can't replicate it anymore. Should have created a live example with compiler explorer at that time. Sorry.
