### ISSUE TITLE
Non-word-boundary matches at start and end of string

### ISSUE THREAD

**Issue by JubilantJerry** [boostorg/regex#123]
According to the documentation, "\B" matches locations that are not at word boundaries. The behavior is inconsistent with the description at the start and end of strings, however.

Example code:
```
#include <iostream>
#include <boost/regex.hpp>

int main() {
    const char* subject_non_word = "!";
    const char* pattern_non_word = "\\B";
    boost::regex regex_non_word = boost::regex(pattern_non_word);
    std::cout << boost::regex_search(subject_non_word, regex_non_word) << std::endl;

    const char* subject_word = "a";
    const char* pattern_word = "\\b";
    boost::regex regex_word = boost::regex(pattern_word);
    std::cout << boost::regex_search(subject_word, regex_word) << std::endl;
}
```

The output, tested on Boost 1.75.0:
```
0
1
```

If we interpret the wording as saying "\B" represents all locations that are not matched by "\b", then this is not the correct behavior since "\b" does not match the start and end of the string when the subject is "!".

If we only consider locations between two characters as eligible for being or not being word boundaries, then it's inconsistent that the start and end of the string are considered word boundaries when the subject is "a".

If we assume there are invisible characters before and after the string, then those invisible characters must neither be word characters nor non-word characters. If they are word characters, then there are no word boundaries when the subject is "a". If they are non-word characters, then when the subject is "!" the start and end of the string represent locations between two non-word characters and should match "\B".

**Comment by jzmaddock** [comment]
The intention was that \B matches a non-word boundary *within* a word.  However, I see that perl interprets it more as you do, so I'll fix that shortly.
