### ISSUE TITLE
w32_regex_traits.hpp unconditionally defines WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by ngladitz** [boostorg/regex#127]
While trying to update to Boost 1.76.0 I started getting warnings in MSVC windows builds:
```
boost/regex/v5/w32_regex_traits.hpp(33): warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition
```

I don't directly use boost/regex; I think ASIO is pulling it in.

The project globally defines `WIN32_LEAN_AND_MEAN`. 
`w32_regex_traits.hpp` also (unconditionally) defines the macro leading to the above redefinition warning.

Presumably the header should check for `WIN32_LEAN_AND_MEAN` before defining it.
Same for `VC_EXTRALEAN`.

Perhaps also make the definition opt-out in case someone needs the non-lean-and-mean version(?).
ASIO seems to use `BOOST_ASIO_NO_WIN32_LEAN_AND_MEAN` for this.

**Comment by jzmaddock** [comment]
Confirmed.
