### ISSUE TITLE
regex dead loop

### ISSUE THREAD

**Issue by SMSEP** [boostorg/regex#140]
I ran into a freeze when using regular expressions.
this is my program：

#include \<cstdio\>
#include \<iostream\>
using namespace std;

#include \<boost/regex.hpp\>

int main()
{
       boost::regex e(string("1?+(?#)1"));
       return 0;
}

**Comment by SMSEP** [comment]
@jzmaddock  
hi, please check it

**Comment by jzmaddock** [comment]
Confirmed.
