### ISSUE TITLE
Consider using boost.winapi to wrap windows.h instead of including it

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [boostorg/regex#144]
I'm not sure if you're aware, but [Boost.WinAPI](https://github.com/boostorg/winapi) exists as a means for boost libs to invoke winapi methods without actually including the header. The change to a header only lib in 1.76 has managed to break every single project I use Boost.Regex in, as I was under the assumption it was a "safe" (in terms of not polluting the global namespace) header to include.

**Comment by jzmaddock** [comment]
WinAPI doesn't have what I need - that was the first place I looked!

**Comment by Ryan-rsm-McKenzie** [comment]
Have you considered opening an issue to have them added?

**Comment by jzmaddock** [comment]
Fixed in develop.
