### ISSUE TITLE
error C2027: use of undefined type 'boost::mpl::bool_<false>'

### ISSUE THREAD

**Issue by PhoebeHui** [boostorg/regex#145]
Hi All,

We encountered 'error C2027: use of undefined type 'boost::mpl::bool_<false>'' when use '#include <boost/regex/v4/regex.hpp>', it looks a source issue, could you please take a look? Thanks!

**Environment**: boost 1.76 +  VS2019 + C++17

**Repro code:**
#include <boost/regex/v4/regex.hpp>
#include <iostream>

int main()
{
    std::cout << "Hello World!\n";
}

**Failures**:
```
.\boost\regex\v4\basic_regex_parser.hpp(59,116): error C2027: use of undefined type 'boost::mpl::bool_<false>'
```

Related to https://github.com/microsoft/vcpkg/issues/19153

**Comment by jdx-john** [comment]
I'm the original reporter, just for further information this is an old code-base and honestly, I don't know _why_ we are using v4 rather than just boost/regex.hpp. Using the latter, compilation succeeds but I do not understand what difference it makes.

**Comment by jzmaddock** [comment]
What you're doing isn't (and never has been) supported.  In short please include boost/regex.hpp.

**Comment by jdx-john** [comment]
Thanks @jzmaddock. I wondered as much although it's been in our codebase a dozen years as far as I know.

**Comment by jzmaddock** [comment]
> Thanks @jzmaddock. I wondered as much although it's been in our codebase a dozen years as far as I know.

I realise that, however the "V4" code is all C++03, and has now been deprecated, and will most likely be removed entirely sometime next year.  At that point your code really will break!  In general, please don't use internal/private/undocumented headers as they will almost certainly break at some point I'm afraid :(

**Comment by PhoebeHui** [comment]
@jzmaddock, thanks for your response!
