### ISSUE TITLE
boost regex constructor is not throwing boost::regex_constants::error_badbrace in boost-1.66.0-10.el8.x86_64

### ISSUE THREAD

**Issue by lohitendu2000** [boostorg/regex#179]
This following program I have compiled and run in two versions of boost, which is boost-1.53.0-27.el7.x86_64 and boost-1.66.0-10.el8.x86_64

#include <boost/regex.hpp>
#include <string>
#include <iostream>

int main()
{
   try {
         std::string value = "^[a-z0-9]{,4}$";
         boost::regex pattern(value);
   }
   catch (boost::regex_error &e)
   {
     std::cout<<"the error caught is "<<e.what()<<std::endl;
     return 0;
   }
   std::cout<<"no error caught"<<std::endl;
   return 0;
}

Output when boost is in version 1.53
the error caught is Invalid content of repeat range.  The error occurred while parsing the regular expression: '^[a-z0-9]{>>>HERE>>>,4}$'

Output when boost is in version 1.66
no error caught

I am expecting the error thrown in 1.66 version to be same as error thrown in 1.53. It looks like in 1.66 version no error is thrown.

**Comment by jzmaddock** [comment]
That's correct: I think the Perl regex engine changed and we eventually caught up: {,4} means "repeat up to 4 times", so the same as {0,4}.

Please re-open if I've misunderstood.

**Comment by lohitendu2000** [comment]
Ok but, when I change the value from std::string value = "^[a-z0-9]{,4}$"; to this: std::string value = "^[a-z0-9]{a,z}$"; in the same sample program, then also there is a difference.

Output when boost is in version 1.53
the error caught is Invalid content of repeat range.  The error occurred while parsing the regular expression: '^[a-z0-9]{>>>HERE>>>a,z}$'.
Output when boost is in version 1.66
no error caught

**Comment by lohitendu2000** [comment]
I also think a{4,} where a can be repeated at least 4 times and then is no upper limit. But should a{,4} be treated as a valid pattern at all? 0 and no lower limit is not same.

The boost documentation also mentions only about missing upper limit but not about missing lower limit.

**Comment by jzmaddock** [comment]
> Ok but, when I change the value from std::string value = "^[a-z0-9]{,4}$"; to this: std::string value = "^[a-z0-9]{a,z}$"; in the same sample program, then also there is a difference.

Very old bug fix: https://svn.boost.org/trac10/ticket/8569

Basically { followed by illegal quantifiers is treated as a literal.  This is for compatibility with what Perl does.

>ut should a{,4} be treated as a valid pattern at all? 0 and no lower limit is not same.

Sigh.  Like you I like strong error handling, but we promise to do what Perl does.

>The boost documentation also mentions only about missing upper limit but not about missing lower limit.

I don't think the Perl docs mention this either, it doesn't mean there is no lower bound, here the { is treated as a literal as in the {a,z} case.

**Comment by lohitendu2000** [comment]
Ok, In the first case I can see that from perl 5.34.0 version {,x} is accepted as an enhancement: https://perldoc.perl.org/5.34.0/perldelta
Therefore no issues in first case.

But for {a,z} case I have tested following program in perl 5.34.0 version:

#!/usr/bin/env perl
use strict;
use warnings;
while (<>) {   # Read input from command-line into default variable $_
   print /^[a-z0-9]{a,z}$/ ? "Accept\n" : "Reject\n";
}

And following is the output:
./try_1.pl
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/^[a-z0-9]{ <-- HERE a,z}$/ at ./try_1.pl line 6.

So I dont think perl latest version also accepts this as a literal and backtracks it? But it throws error as above. If Perl throws error, then why boost treats it as literal and backtracks it? Also is that documented in boost? If documented where can I find that please?

**Comment by jzmaddock** [comment]
OK, it looks like Perl has changed.

This behaviour was introduced as a result of this bug report: https://svn.boost.org/trac10/ticket/8569 as Perl always used to treat the { as a literal if not part of a valid repeat range.  I'll investigate what current Perl does.
