### ISSUE TITLE
Regex bug  - possibly due to non-greedy dot capture

### ISSUE THREAD

**Issue by nikess** [boostorg/regex#182]
Boost 1.80. 

Possibly the cause is something to do with whitespace handling, possibly the non-greedy.

Regex = "oid_lo=(.*?) "

For input data "oid_lo=123 oid_ex=455"
:

```
boost::regex regex_oid_lo("oid_lo=(.*?) "s);
boost::smatch regex_oid_lo_matches;
if (boost::regex_search("oid_lo=123 oid_ex=455"s, regex_oid_lo_matches, regex_oid_lo)) {

        cout << regex_oid_lo_matches.size() << endl;
        cout << regex_oid_lo_matches[0] << endl;
        cout << regex_oid_lo_matches[1] << endl;
    }else{
        cout << "no match" << endl;
}
```

This returns true for the regex_search, and yet regex_oid_lo_matches is not populated correctly - it contains garbage. Different every run.

Expected: returns true for search, and regex_oid_lo_matches[1] == "123".

For input data "oid_lo=123 " it works as expected, matching oid_lo=123 correctly and "123" being in regex_oid_lo_matches[1]

```
boost::regex regex_oid_lo("oid_lo=(.*?) "s);
boost::smatch regex_oid_lo_matches;
if (boost::regex_search("oid_lo=123 "s, regex_oid_lo_matches, regex_oid_lo)) {

        cout << regex_oid_lo_matches.size() << endl;
        cout << regex_oid_lo_matches[0] << endl;
        cout << regex_oid_lo_matches[1] << endl;
    }else{
        cout << "no match" << endl;
}
```

**Comment by jzmaddock** [comment]
There's a bug in your code: the `boost::smatch` is populated with iterators into the string being matched, but the lifetime of your string does not extend beyond the function call, so the iterators point to invalid (freed) memory.
