### ISSUE TITLE
using regex_search matching wchar_t strings may cause crashes or dead loops

### ISSUE THREAD

**Issue by 951193102** [boostorg/regex#192]
wchar_t * test = L"11111";  
const wchar_t *  matchTestStart = (const wchar_t*)test;
	const wchar_t *  matchTestEnd = (const wchar_t*)((char*)test + sizeof(test) + 1);
	while (boost::regex_search(wmatchTestStart,wmatchTestEnd, what, reg)) {
		printf("%ws", (what[0]));
	}

**Comment by jzmaddock** [comment]
Please post a self contained example that actually compilers - for example what is the actual expression used?

**Comment by 951193102** [comment]
I don't quite understand what you're saying,The problem is that the wchar_t type memory length is not aligned.

**Comment by stefankueng** [comment]
have the same (or similar) problem:

```
std::wstring fileString = L"abcdefghijklmnopqrstuvwxyz";
auto start              = fileString.cbegin();
auto end                = fileString.cend();
boost::match_results<std::wstring::const_iterator> whatC;
boost::match_flag_type flags = boost::match_default | boost::format_all | boost::match_not_dot_newline;
int ft = boost::regbase::icase;
boost::wregex  searchRe = boost::wregex(L"^test", ft);
int nFound = 0;
while (boost::regex_search(start, end, whatC, searchRe, flags))
{
    nFound++;
}

```

The problem appears to be the '^' in the search string. This results in the iterator being decremented before begin().

compiled with MSVC (Visual Studio 17.6) and boost 1.82.0

**Comment by lifenjoiner** [comment]
> The problem appears to be the '^' in the search string. This results in the iterator being decremented before begin().

Also traced into this, out of range:
https://github.com/boostorg/regex/blob/237e69caf65906d0313c9b852541b07fa84a99c1/include/boost/regex/v5/perl_matcher_common.hpp#L372-L375

...
Finally, found the `match_prev_avail` flag was set accidentally...

**Comment by jzmaddock** [comment]
```
   while (boost::regex_search(start, end, whatC, searchRe, flags))
   {
      nFound++;
   }
```

This *will* infinite loop since `start` is never updated in the loop body.  That aside this works fine for me.

> Finally, found the match_prev_avail flag was set accidentally...

So is this still an issue or not?

**Comment by lifenjoiner** [comment]
> > Finally, found the match_prev_avail flag was set accidentally...
> 
> So is this still an issue or not?

No for https://github.com/stefankueng/grepWin/issues/405, where I came from, at least.

> That aside this works fine for me.

Me too.

**Comment by jzmaddock** [comment]
Please reopen if someone can post a reproducer.
