### ISSUE TITLE
Insufficient State Limit for Resolving Regex

### ISSUE THREAD

**Issue by MarcoDeMeco** [boostorg/regex#194]
Boost 1.74
Using the following regex
^\s*((\s?\S+)+)\s*$
with the input "Intel Corporation", the library throws an error because the corresponding heuristic has generated a lower state limit than the number of states required to solve the regex. I'm wondering if it's possible to adjust this heuristic to provide a slightly higher number of states so that this regex can be resolved by the library.

**Comment by jzmaddock** [comment]
This looks to be working OK in current releases.  Please reopen if it re-surfaces.
