### ISSUE TITLE
Security Findings in Boost.Regex

### ISSUE THREAD

**Issue by TheZ3ro** [boostorg/regex#203]
Dear Boost.Regex maintainers,
during a recent audit arranged by [OSTIF](https://ostif.org), we identified some security issues in your library.

We tried to get in touch with @jzmaddock who is the main point of contact in the [Boost.Regex page](https://www.boost.org/doc/libs/) on the Boost website and in the [libs/maintainers.txt](https://github.com/boostorg/boost/blob/master/libs/maintainers.txt#L137) file without success.

Before moving on with making all the findings public we are opening this issue to check if we can reach a maintainer to share the security issues in a safe way.

You can reach back to us at research[at]shielder[dot]com

Thanks,

**Comment by jzmaddock** [comment]
Message sent.
