### ISSUE TITLE
Cmake not building libboost_regex.a

### ISSUE THREAD

**Issue by Duron27** [boostorg/regex#213]
Not sure why,  it used to I thought
And if i let it build everything regex is still missing
cmake ../  -DBOOST_INCLUDE_LIBRARIES="filesystem;program_options;iostreams;regex"

**Comment by jzmaddock** [comment]
Other than some deprecated legacy stuff, the separate library hasn't been needed for a few releases now (it's header only).

**Comment by Duron27** [comment]
Ok thanks
