### ISSUE TITLE
'$' or '\Z' Can Match Multiple Times In Regex

### ISSUE THREAD

**Issue by nllyy** [boostorg/regex#226]
```C++
#include <iostream>
#include <boost/regex.hpp>
using namespace std;
using namespace boost;
int main()
{
	string str = "A";
	regex r(R"(A?$)");	//or A?\Z
	str = regex_replace(str, r, "E");
	cout << str;
	return 0;
}
```
It will output "EE", but when I use std::regex, the output is "E".
It seems that “$” can be matched multiple times in boost, is this by design? Or is it a bug?

**Comment by jzmaddock** [comment]
This is by design: the first match matches the "A", the second the null string after the "A".  This is the way Perl and all compatible matchers do it.  I'm not sure why the std isn't, IMO it should be ;)
