### ISSUE TITLE
syntax name change

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#35]
and could you please change ecmascript to Javascript?

**Comment by jzmaddock** [comment]
On 27/07/2017 19:32, jmichae3 wrote:
>
> and could you please change ecmascript to Javascript?
>

Why?  ECMA script is the correct name, and it's what the C++ std mandates.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by jmichae3** [comment]
because Javascript was the language's original name and still is. and has more features than ecmascript.

**Comment by jzmaddock** [comment]
We make no promises to match Javascript (which comes in several different flavours), only ECMAScript.
