### ISSUE TITLE
std::regex::extended does not work

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#36]
'bout as simple as that. format_sed doesn't work either. the only syntax that works is ecmascript.

**Comment by jzmaddock** [comment]
On 27/07/2017 19:33, jmichae3 wrote:
>
> 'bout as simple as that. format_sed doesn't work either. the only 
> syntax that works is ecmascript.
>

Sure it does, it gets tested every night too, please provide concrete 
cases of "not working".

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by jmichae3** [comment]
then it might be mingw-w64 compiler.

**Comment by jzmaddock** [comment]
I doubt it's the compiler, as I said, suggest you post a test case.

**Comment by jzmaddock** [comment]
Closing for lack of information.
