### ISSUE TITLE
Word boundaries assertion behaviour at subject start/end do not match documentation

### ISSUE THREAD

**Issue by mawww** [boostorg/regex#40]
Hello,

According to the documentation, using `match_not_bow` means `\b` will not match at [first,first], however the code seems to treat it as "*(first)-1 is a word character", leading to a different behaviour.

For example I'd expect `\b` not to match anything given the subject `-` and `match_not_bow`, but the current implementation does find an empty match at the subject begin. The same behaviour can be observed as subject end with `match_not_eow`.

Cheers,

Maxime.

**Comment by jzmaddock** [comment]
You're correct: this is a bug.  Fixed in the commit referenced above.
