### ISSUE TITLE
std::thread does not work in struct

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#41]
try putting std::thread in struct and later trying to fill in blanks. it can't be done.
also, you have to CloseHandle() in windows when thread is done and people don't know this. which may explain any server resource leaks. that you can't do without a vector or array of struct.

**Comment by jmichae3** [comment]
- need to be able to instantiate an empty object at the start and fill in thread function and run it and maybe even close it later, even within a struct.
- constructor should not require running and configuring the thread upon instantiation.
- std::thread.nativeHandle() should allow someone to CloseHandle() on windows.

**Comment by jzmaddock** [comment]
What has this to do with Boost.Regex?

**Comment by jmichae3** [comment]
sorry, wrong group
