### ISSUE TITLE
std::thread lacks GetActiveProcessorCount() and GetMaximumProcessorCount()

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#42]
std::thread lacks GetActiveProcessorCount() and GetMaximumProcessorCount() or equivalent methods to find out how many threads or processors there are in the computer. without that information it's too easy to overload the box with too many threads and it gets really slow.

**Comment by jmichae3** [comment]
you may wish to include group processor counts as well - some vendors require those.

**Comment by jzmaddock** [comment]
What has this to do with Boost.Regex?
