### ISSUE TITLE
need std::thread functionality in __DOS__ and __DJGPP__

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#43]
should be functional in #if defined(__DOS__)&&(defined(__WATCOMC__)||defined(__MARSC)||defined(__DJGPP__)) compilers - all they have now is fsu pthreads and pth which I think are timer-based.
compiling for DOS requires a 32-bit Windows OS currently. maybe not for Mars C/C++.
please consider this.

**Comment by jzmaddock** [comment]
What has this to do with Boost.Regex?

**Comment by jmichae3** [comment]
this was for std::thread sorry.
