### ISSUE TITLE
A bit too many Travis OS X jobs

### ISSUE THREAD

**Issue by pdimov** [boostorg/regex#47]
Mac OS X jobs on Travis are a bottleneck, so you might wish to consider lowering their number somewhat. :-)

**Comment by pdimov** [comment]
Also, the new `cxxstd` feature of Boost.Build allows one to simplify considerably, see f.ex. https://github.com/boostorg/smart_ptr/commit/e88227b5063ac7f05183327346567a2393e3a23d

**Comment by jzmaddock** [comment]
Duly lowered.

The ability to test multiple std values in one go is great, but probably not applicable in this case as I suspect the tests would just time out if we try to test too many variants in go?

**Comment by pdimov** [comment]
Looking at https://travis-ci.org/boostorg/regex/builds/292223115, the jobs don't take that much time, so it should be possible to run them two at a time, if not four. The Travis job limit is 49 minutes, and there's some common startup time that will be saved.
