### ISSUE TITLE
start over from scratch, try LALR(1) parser and state machine, std::regex does not work at all, period, on any compiler.

### ISSUE THREAD

**Issue by jmichae3** [boostorg/regex#56]
read a book on LALR(1) parsers and how to make one using function-driven productions.
read a book on how to make a state machine. forget about the license in the front of the book, they rakeholdered it until the license is non-valid.

std::regex does not work on any compiler. period.
do not subtract a pointer to the root of memory (crash-proof aint it?)!

**Comment by jzmaddock** [comment]
This has nothing to do with boost::regex.
