### ISSUE TITLE
Build Error Emscripten

### ISSUE THREAD

**Issue by jspears** [boostorg/regex#59]
When running 

```
./b2 toolset=emscripten --with-regex
```
It errors with
```
Performing configuration checks

    - 32-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : no  (cached)
    - combined                 : no  (cached)

Building the Boost C++ Libraries.


    - symlinks supported       : yes (cached)
Error: ambiguity found when searching for best transformation
Trying to produce type 'SEARCHED_LIB' from: 
Generators that succeeded:
 -  searched-lib-generator
 -  emscripten.searched-lib-generator
First generator produced: 
 -  { %.no-action-icuuc.SEARCHED_LIB }
Second generator produced: 
 -  { %.no-action-icuuc.SEARCHED_LIB }
```
OS: OSX -10.12.6
Compiler: emcc (Emscripten gcc/clang-like replacement) 1.37.33 ()

Most boost libraries build fine using the ./b2 toolset=emscripten --with-*  though graph
iostreams,
locale,
log,
python,
regex,
stacktrace
 Fail in the same way.   

Perhaps this is a b2 problem.    I'm new to C++ so it is probably me...

**Comment by jspears** [comment]
Ah sorry the docs had the --disable-icu and didn't fugure how that mapped to this issue; Closing, thanks.

**Comment by ofloveandhate** [comment]
what was the solution to this problem?  i just encountered it when trying to build boost 1.67 with emscripten 1.38.8 on OSX

**Comment by jspears** [comment]
apparently it had to do with --disable-icu.   I don't exactly remember.  The answer was in the error message ```%.no-action-icuuc.SEARCHED_LIB ``` .

**Comment by ofloveandhate** [comment]
ah ok.  i tried `--disable-icu` and it yielded almost the same error, so something additional is up for me.  i think i'll investigate what you indicate, and possibly raise the issue at boost/build.  thanks!

**Comment by volo-zyko** [comment]
BTW, for me the following change fixed the "ambiguity found when searching for best transformation" error:

```diff
--- tools/build/src/tools/emscripten.jam
+++ tools/build/src/tools/emscripten.jam
@@ -6,6 +6,7 @@
 import feature ;
 import os ;
 import toolset ;
+import generators ;
 import common ;
 import gcc ;
 import type ;
@@ -52,6 +53,8 @@
         <debug-symbols>off <debug-symbols>on
         <rtti>off <rtti>on
         ;
+generators.override builtin.lib-generator : emscripten.prebuilt ;
+generators.override emscripten.searched-lib-generator : searched-lib-generator ;
 
 type.set-generated-target-suffix EXE : <toolset>emscripten : "js" ;
 type.set-generated-target-suffix OBJ : <toolset>emscripten : "bc" ;
 
```

**Comment by werto87** [comment]
SwimmingTiger and volo-zyko solution worked for me.
Note: I had to change the suffix from ".bc" into ".a" to use the lib with cmake on *unix.

**Comment by jzmaddock** [comment]
Just to add, that with the latest Boost release, regex is header only for C++11 and up, so building it is unnecessary.

**Comment by jackw1111** [comment]
I was able to compile boost::python for emscripten using the info from SwimmingTiger and volo-zyko as well. 
One thing to mention was that I was getting the error `# error unknown multiarch location for pyconfig.h` and had to use `pyconfig.h` generated from compiling python for emscripten (I followed this open source project [here](https://github.com/python-emscripten/python), but It would probably work if you have built python with the emscripten toolchain already). 

I couldn't figure out how to set the custom python include path to the new pyconfig.h location
so i just temporarily overrode pyconfig.h at /usr/include/python2.7 with the custom pyconfig.h
and built and the error for multiarch suport for pyconfig.h was gone.

**Comment by mpconte** [comment]
On building boost 1.75.0 with the emscripten toolset and following the comments here to build, I still get the following error in the `./b2 `step:
```

wasm-ld: error: unknown argument: -h
wasm-ld: error: unknown argument: -Bstatic
wasm-ld: error: unknown argument: -Bdynamic
```
