### ISSUE TITLE
boost::regex   with unmatched parenthesis emits error with spelling error

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [boostorg/regex#69]
I made a typo in a regex:

    boost::regex tty_filter( "^tty\\.usbmodem([[:digit:]]+)$" );

and got this exception:

    libc++abi.dylib: terminating with uncaught exception of type 
    boost::exception_detail::clone_impl<boost::exception_detail:: 
    error_info_injector<boost::regex_error> >: Found a closing ) with no corresponding 
    openening parenthesis.  The error occurred while parsing the regular expression fragment: 'digit:]])+>>>HERE>>>)$'.

Note that "opening" is spelled wrong.

There was a pull request to fix this: https://github.com/boostorg/regex/pull/52

**Comment by jeking3** [comment]
This can be closed - the PR was merged.
