### ISSUE TITLE
boost::algorithm::split_regex hangs and consumes CPU on dangling alternatives

### ISSUE THREAD

**Issue by directionless** [boostorg/regex#76]
I happened to typo a regex, and I noticed that `boost::algorithm::split_regex` started consuming a bunch of CPU. I don't know is this would have eventually caught itself and terminating. The regex in question was `;|`, and this appears to be true for any dangling `|`. 

I'm a bit surprised that `boost::regex` allowed `;|` as valid, given split_regex's behavior. 

Simple example up at https://gist.github.com/directionless/c38eb7dc216bcd93b40c3ecaf99f326e

I tested this on darwin with boost 1.67, and on linux with boost 1.65

**Comment by jzmaddock** [comment]
Sorry to split hairs, but can you please file this bug against Boost.Algorithm?

There are a number of regular expressions which can successfully match zero characters - for example "^", and I've confirmed that these all break Boost.Algorithm.

With regard to ";|" being allowed: it wasn't historically, but was changed for Perl compatibility.  It does have a small number of legitimate uses, perhaps a more obvious example would be ";|^" which treats ";" plus line-starts as separators, and again can match zero characters.

**Comment by directionless** [comment]
Filed as https://github.com/boostorg/algorithm/issues/68

At this point, my buzzers are _also_ finding this bug.
