### ISSUE TITLE
case insensitive on swedish characters are not working

### ISSUE THREAD

**Issue by Sopor** [boostorg/regex#94]
I'm involved in a project that use boost and i have notice something with regex that is not working as it should, but i don't know if the issue is in boost or in the program that use boost. I'm not a programmer myself so i need to ask.

When using (?i) that make a regex case insensitive it will work, but not on Swedish characters as `å, ä, ö and Å, Ä, Ö`. It will think these are two different chars. Same thing if i use a dot `.` that should represent any char, but it won't do that on these six chars.

So could this be an issue in boost?

**Comment by JohnAlt2** [comment]
Not an expert, but before suspecting Boost I would suspect the Unicode library being used with Boost RegEx and the configuration of it. AFAIK it is the Unicode library that mostly defines the properties and associations of characters.

**Comment by Sopor** [comment]
@JohnAlt2 If i do as you suggested with `XÖX` and `X.*?X`, it will be not a match.

I tried with other non-ASCII chars and it will be the same, not a match.

**Comment by JohnAlt2** [comment]
Strange, though I can think of a possible cause why the test failed. Try data "XXXXXÖXXXXX" and regex "X[^X]+X". Also as sanity check with test data "XXXXXaXXXXX" to ensure test is at least working with ASCII chars.
But you should get the idea, experiment to find the boundaries of the behaviour.
Also you could try and get your software to output the loaded data as a binary dump of some sort and output any matched string.

**Comment by jzmaddock** [comment]
I think you need to take this back to the programmers that are integrating Boost into the application - Boost.Regex is perfectly capable of matching non-ASCII characters, but it does need to be configured correctly (is it using ICU?  Or win32_regex_traits?), and programmed correctly (what's the input text format?  Is regex seeing full UTF-32 code points, or UTF-8 partial characters?).  So I would need a lot more details about how the library is being used before I could offer a solution.

**Comment by Sopor** [comment]
It seems to be `win32_regex_traits`, but i will close this because it probably is not boost fault. Thanks you all for the info.

**Comment by Sopor** [comment]
It seems that you need two dots to match å, ä or ö because they are two chars put together. But why does it work when i test it in a regex testers? RegexBuddy do support Boost 1.66-1.68 and to match any of the chars i only need one dot. Can someone confirm that boost need two dots to match å, ä and ö?

**Comment by JohnAlt2** [comment]
Ah! That might actually make sense. 
I believe that accented characters such as "Ä" can be encode as either a single character U+00C4 or as a base letter "A" U+0041 plus a combining character U+0308 (https://unicode-table.com/en/0308/) which is just the accent (two floating dots) without and letter. This is rendered in display as a single "Ä" character. This is something you should be able to test.
I suspect just the act of copying or pasting may convert the two characters in to a single character for compatibility purposes.
See https://en.wikipedia.org/wiki/Combining_character
If this is the case you might want to look at what Unicode library is being used, what library configurations are being used to handle international characters or equivalences (an area of ignorance for me). Alternatively have some pre-processing done to convert these combining characters, though I suspect should not be needed.
(Note: I am not an expert in this area, Unicode and localisation is just something I stumble against occasionally)
